***************
*** 33,40 ****
  
  # try to infer the correct GCCPREFIX
  ifndef GCCPREFIX
- GCCPREFIX := $(shell if i386-jos-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
-    then echo 'i386-jos-elf-'; \
     elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
     then echo ''; \
     else echo "***" 1>&2; \
--- 33,40 ----
  
  # try to infer the correct GCCPREFIX
  ifndef GCCPREFIX
+ GCCPREFIX := $(shell if i386-elf-objdump -i 2>&1 | grep '^elf32-i386$$' >/dev/null 2>&1; \
+    then echo 'i386-elf-'; \
     elif objdump -i 2>&1 | grep 'elf32-i386' >/dev/null 2>&1; \
     then echo ''; \
     else echo "***" 1>&2; \
